s="Tops Technologies"

print(len(s))
print(s)
print(s.capitalize())
print(s.casefold())
print(s.upper())
print(s.lower())
print(s.swapcase())
print(s.center(40,"&"))
print(s.count("T"))
print(s.endswith("es"))
print(s.startswith("To"))
print(s.find("log"))
print(s.index("T",1))
print("tops123".isalnum())
print("123".isalnum())
print("tops".isalnum())
print("tops 123".isalnum())
print("tops1".isalpha())
print("123".isnumeric())
print(s.istitle())
print("TOPS".isupper())
print("tops".islower())
print(" ".isspace())
print("Hello".replace("l","w"))
print(dir(s))
